eFilms/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Models
{
    public class Actor
    {
        //Attributes
        [Key]
        public int ActorId { get; set; }
        [Display(Name = "Full Name")]
        public string FullName { get; set; }
        [Display(Name = "Biography")]
        public string Bio { get; set; }
        [Display(Name = "Actors Picture")]
        public string ProfilePictureURL { get; set; }

        //Relationships
        public List<FilmActors> FilmActors { get; set; }
    }
}

eFilms/Models/Director.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Models
{
    public class Director
    {
        //Attributes
        [Key]
        public int DirectorId { get; set; }
        [Display(Name = "Full Name")]
        public string FullName { get; set; }
        [Display(Name = "Biography")]
        public string Bio { get; set; }
        [Display(Name = "Directors Picture")]
        public string ProfilePictureURL { get; set; }

        //Relationships
        public List<Film> Films { get; set; }

    }
}

eFilms/Models/ErrorViewModel.cs
using System;

namespace eFilms.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

eFilms/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using eFilms.Data.Enums;

namespace eFilms.Models
{
    public class Film
    {
        //Attributes
        [Key]
        public int FilmId { get; set; }

        [Display(Name = "Film Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Film Cover")]
        public string FilmCoverURL { get; set; }

        [Display(Name = "Release Date")]
        public DateTime ReleaseDate { get; set; }

        [Display(Name = "Price")]
        public double Price { get; set; }

        [Display(Name = "Genre")]
        public FilmCategory FilmCategory { get; set; }

        //Relationships
        public List<FilmActors> FilmActors { get; set; }

        public List<StoreFilms> StoreFilms { get; set; }

        [ForeignKey("DirectorId")]
        public int DirectorId { get; set; }
        public Director Director { get; set; }

    }
}

eFilms/Models/FilmActors.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Models
{
    public class FilmActors
    {
        public int FilmId { get; set; }
        public Film Film { get; set; }

        public int ActorId { get; set; }
        public Actor Actor { get; set; }
    }
}

eFilms/Models/Store.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Models
{
    public class Store
    {
        //Attributes
        [Key]
        public int StoreId { get; set; }

        [Display(Name = "Store Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
        public string StoreLogoURL { get; set; }

        //Relationships
        public List<StoreFilms> StoreFilms { get; set; }

    }
}

eFilms/Models/StoreFilms.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Models
{
    public class StoreFilms
    {
        public int StoreId { get; set; }
        public Store Store { get; set; }

        public int FilmId { get; set; }
        public Film Film { get; set; }
    }
}

eFilms/Controllers/ActorsController.cs
using eFilms.Data;
using eFilms.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Controllers
{
    public class ActorsController : Controller
    {
        //readonly Db context
        private readonly ApplicationDbContext context;

        //Constructor for the controller
        public ActorsController(ApplicationDbContext _context)
        {
            context = _context;
        }

        //Function for the index page
        //Synchronous
        public IActionResult Index()
        {
            //Gets a list of the data from the actors table
            List<Actor> data = context.Actors.ToList();
            //Returns the view
            return View(data);
        }
    }
}

eFilms/Controllers/DirectorsController.cs
using eFilms.Data;
using eFilms.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Controllers
{
    public class DirectorsController : Controller
    {
        //readonly Db context
        private readonly ApplicationDbContext context;

        //Constructor for the controller
        public DirectorsController(ApplicationDbContext _context)
        {
            context = _context;
        }

        //Asynchronous function for the index
        public async Task<IActionResult> Index()
        {
            List<Director> data = await context.Directors.ToListAsync();
            return View(data);
        }
    }
}

eFilms/Controllers/FilmsController.cs
using eFilms.Data;
using eFilms.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Controllers
{
    public class FilmsController : Controller
    {
        //readonly Db context
        private readonly ApplicationDbContext context;

        //Constructor for the controller
        public FilmsController(ApplicationDbContext _context)
        {
            context = _context;
        }

        //async
        public async Task<IActionResult> Index()
        {
            List<Film> data = await context.Films.Include(n => n.StoreFilms).OrderBy(n => n.Name).ToListAsync();
            return View(data);
        }
    }
}

eFilms/Controllers/StoresController.cs
using eFilms.Data;
using eFilms.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eFilms.Controllers
{
    public class StoresController : Controller
    {
        //readonly Db context
        private readonly ApplicationDbContext context;

        //Constructor for the controller
        public StoresController(ApplicationDbContext _context)
        {
            context = _context;
        }

        //async
        public async Task<IActionResult> Index()
        {
            List<Store> data = await context.Stores.ToListAsync();
            return View(data);
        }
    }
}

eFilms/Views/Actors/Index.cshtml
<!--Define Model-->
@model IEnumerable<Actor>

<!--Define ViewData-->
@{
    ViewData["Title"] = "List of Actors";
}

<!--HTML code-->

<h1>Welcome to the Actors view</h1>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr>
                    <!--You can either hard code the column name or get it from the model-->
                    <!--<th>Actor Picture</th>-->
                    <th>@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Actor actor in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@actor.ProfilePictureURL" style="max-width:150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => actor.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => actor.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-primary text-white">
                                <i class="badge-info bi-pencil-square"></i>
                                Edit
                            </a>
                            <a class="btn btn-info text-white">
                                <i class="badge-info bi-eye"></i>
                                Details
                            </a>
                            <a class="btn btn-danger text-white">
                                <i class="badge-info bi-trash"></i>
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

eFilms/Views/Directors/Index.cshtml
@model IEnumerable<Director>
@{
    ViewData["Title"] = "List of Directors";
}

<!--HTML code-->

<h1>Welcome to the Directors view</h1>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr>
                    <!--You can either hard code the column name or get it from the model-->
                    <!--<th>Actor Picture</th>-->
                    <th>@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Director director in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@director.ProfilePictureURL" style="max-width:150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => director.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => director.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-primary text-white">
                                <i class="badge-info bi-pencil-square"></i>
                                Edit
                            </a>
                            <a class="btn btn-info text-white">
                                <i class="badge-info bi-eye"></i>
                                Details
                            </a>
                            <a class="btn btn-danger text-white">
                                <i class="badge-info bi-trash"></i>
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

eFilms/Views/Films/Index.cshtml
<!--Define Model-->
@model IEnumerable<Film>

<!--Define ViewData-->
@{
    ViewData["Title"] = "List of Films";
}

<!--HTML code-->

<h1>Welcome to the Films view</h1>

<div class="row">
    @foreach (Film film in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @film.Name
                                    <a class="text-white float-right">
                                        <i class="bi-eye bi-pencil-square"></i>
                                    </a>
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@film.FilmCoverURL" width="100%" alt="" />
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@film.Description</p>
                            <p class="card-text"><b>Store: </b>@film.StoreFilms</p>
                            <p class="card-text"><b>Category: </b>@film.FilmCategory</p>                            <p class="card-text">Description Sample</p>
                            <p class="card-text"><b>Release Date: </b>@film.ReleaseDate.ToString("dd/MM/yy")</p>
                            <p class="card-text">
                                <b>Status: </b>
                                @if (DateTime.Now >= film.ReleaseDate)
                                {
                                    <span class="badge bg-success text-white">Available to buy</span>
                                } else
                                {
                                    <span class="badge bg-danger text-white">Not available</span>  
                                }
                            </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right">
                                    <i class="bi bi-eye-fill">
                                        Show Details
                                    </i>
                                </a>
                                <a class="btn btn-success text-white">
                                    <i class="bi bi-cart-plus">
                                        Add to Cart (@film.Price.ToString("c"))
                                    </i>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    }
</div>

eFilms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eFilms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Films" asp-action="Index">eFilms</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-dark" asp-controller="Films" asp-action="Index">
                                <i class="badge-info bi-film"></i>
                                Films
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="button" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i>
                                Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item">
                                    <i class="bi bi-camera-reels" asp-controller="Stores" asp-action="Index"></i>
                                    Stores
                                </a>
                                <a class="dropdown-item">
                                    <i class="bi bi-headset" asp-controller="Directors" asp-action="Index"></i>
                                    Directors
                                </a>
                                <a class="dropdown-item">
                                    <i class="bi bi-person-square" asp-controller="Actors" asp-action="Index"></i>
                                    Actors
                                </a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Films" asp-action="Filter" style="padding-right: 25px">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a film..."/>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                            <i class="bi bi-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - eFilms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

eFilms/Views/Stores/Index.cshtml
<!--Define Model-->
@model IEnumerable<Store>
<!--Define ViewData-->
@{
    ViewData["Title"] = "List of Stores";
}

<!--HTML code-->

<h1>Welcome to the Stores view</h1>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr>
                    <!--You can either hard code the column name or get it from the model-->
                    <!--<th>Actor Picture</th>-->
                    <th>@Html.DisplayNameFor(model => model.StoreLogoURL)</th>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Store store in Model)
                {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@store.StoreLogoURL" style="max-width:150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => store.Name)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => store.Description)
                    </td>
                    <td class="align-middle">
                        <a class="btn btn-primary text-white">
                            <i class="badge-info bi-pencil-square"></i>
                            Edit
                        </a>
                        <a class="btn btn-danger text-white">
                            <i class="badge-info bi-trash"></i>
                            Delete
                        </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>